import { Inter } from "next/font/google";

import Header from "@/components/AddMealHeader/header";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RestaurentLayout({ children }) {
  return (
    <div className={inter.className}>
      <Header />
      {children}
    </div>
  );
}
