import { Inter } from "next/font/google";
import "./globals.css";

// import { I18nextProvider } from "react-i18next";
// import i18n from "../i18n/i18n";
const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <I18nextProvider i18n={i18n}> */}
      <body className={inter.className}>{children}</body>
      {/* </I18nextProvider> */}
    </html>
  );
}
